### ISSUE TITLE
IOException (due to missing <Sample> element in .mzid files ?)

### ISSUE THREAD

**Issue by germa** [PRIDE-Archive/pride-curation-scripts#23] opened 2019-04-11 07:21 UTC
more ./log/validation/1-20190403-PXD013343-RESUB-0001-validation.log

qsdb-3_comprehensive-blib_5ppm.mzid:

Encountered an error executing the step
java.io.IOException: ERROR
        at uk.ac.ebi.pride.submission.AssayFileScanner.findAndMapSummary(AssayFileScanner.java:275)
        at uk.ac.ebi.pride.submission.AssayFileScanner.launchJobAndSubscribe(AssayFileScanner.java:189)
        at uk.ac.ebi.pride.submission.AssayFileScanner.scan(AssayFileScanner.java:117)
        at uk.ac.ebi.pride.curation.tasklet.statistic.AssayFileSummaryItemReader.read(AssayFileSummaryItemReader.java:49)
        at uk.ac.ebi.pride.curation.tasklet.statistic.AssayFileSummaryItemReader.read(AssayFileSummaryItemReader.java:22)

I assume the reason is the missing <Sample> element in the .mzid file

**Comment by germa** [comment] 2019-04-11 07:43
This is a little bit weird, since <Sample> is a required child of the optional <AnalysisSampleCollection> element.
![AnalysisSampleCollection](https://user-images.githubusercontent.com/3297148/55939488-28939880-5c3e-11e9-9037-f7c298de544f.PNG)

**Comment by sureshhewabi** [comment] 2019-04-11 08:30
if you see any IO Exception in the AssayFileScanner.findAndMapSummary, Please check the command I highlighted in the image attached. It should be mostly related with Peak file mismatch
![Screen Shot 2019-04-11 at 09 07 18](https://user-images.githubusercontent.com/5387193/55942436-495aee80-5c3c-11e9-8573-e634e816968a.png)

You can check the peaks parameter in that command:
```
-peaks, /nfs/pride/prod/archive/1-20190403-PXD013343-RESUB-0001/submitted/qExPlus02_00186_OP9 total ex.mgf##/nfs/pride/prod/archive/1-20190403-PXD013343-RESUB-0001/submitted/
qExPlus02_00187_OP9 total ex rosi.mgf,
```
In this case, I see there are spaces in the filename of the mgf file

May be from our pipeline or px submisssion tool we should either restrict  or escape spaces. I will add this to backlog. If you are going to correct it, then the problem is, you need to correct not only peak files name, but also there references in mzIdentML and also in submission.px

**Comment by sureshhewabi** [comment] 2019-04-11 08:43
you need to look into the above command and check whats wrong with peak files
if you do
` grep “<SpectraData ” qsdb-3_comprehensive-blib_5ppm.mzid`

![Screen Shot 2019-04-11 at 09 34 39](https://user-images.githubusercontent.com/5387193/55943233-1d406d00-5c3e-11e9-99e8-cfaaf521f443.png)

it shows 7 peak files in the mzIdentML file
But if you check px summary file, only 2 peak files has been referred
<img width="573" alt="Screen Shot 2019-04-11 at 09 06 27" src="https://user-images.githubusercontent.com/5387193/55943272-2d584c80-5c3e-11e9-8f40-b8fa573bfa07.png">

**Comment by sureshhewabi** [comment] 2019-04-30 08:52
@germa can we close this?

**Comment by sureshhewabi** [comment] 2019-05-03 09:03
@germa I hope this is solved by now and closing the issue.

**Closed as completed by sureshhewabi** 2019-05-03 09:03 UTC
